pipeline:
  publish:
    image: plugins/docker
    privileged: true
    repo: pingu/alfred
    tags: latest
    secrets: [ docker_username, docker_password ]
    build_args: ["--no-cache"]
    when:
      status: [ success ]
      branch: [ master ]
  deploy:
    image: pingu/drone-plugin-kontena:latest
    secrets: [ kontena_token, kontena_url, kontena_grid ]
    kontena_stack: alfred
    when:
      status: [ success ]
      branch: [ master ]
