---
stack: vngu/alfred
version: '0.0.1'
description: alfred
services:
  bot:
    image: pingu/telegram-alfred:latest
    links:
      - lb/lb
    instances: 1
    environment:
      - ALFRED_MONGO_DB_HOST=db
      - ALFRED_MODE=production
    secrets:
      - secret: ALFRED_BOT_TOKEN
        name: ALFRED_BOT_TOKEN
        type: env
  db:
    image: mongo:latest
    instances: 1
    affinity:
      - node==grapefruit
    stateful: yes
    volumes:
      - /srv/alfred/mongo:/data/db
    links:
      - lb/lb
    environment:
      - TZ=Europe/Berlin



